export let REQUEST_LOADER = "REQUEST_LOADER";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_CLIENT_MODAL = "TOGGLE_CLIENT_MODAL"; // FOr Client Dashboard
export const LOGIN_PAGE = "LOGIN_PAGE";
export const PAGE_SCROLL = "PAGE_SCROLL";
export const PAGE_LOADER = "PAGE_LOADER";
export const ADMIN_NAVIGATE = "ADMIN_NAVIGATE";
export const ACCOUNT_NAVIGATE = "ACCOUNT_NAVIGATE";
export const SHIPMENT_NAVIGATE = "SHIPMENT_NAVIGATE";
export const INPUT_HANDLER = "INPUT_HANDLER";
export const REGISTER_INPUT_HANDLER = "REGISTER_INPUT_HANDLER";
export const CLIENT_LOGIN_INPUT_HANDLER = "CLIENT_LOGIN_INPUT_HANDLER";
export const INPUT_FOCUS = "INPUT_FOCUS";


// Account
export const TOGGLE_ACCOUNT = "TOGGLE_ACCOUNT";
export const FETCHED_ACCOUNTS = "FETCHED_ACCOUNTS";

//Services
export const SERVICE_LIST = "SERVICE_LIST";
export const ADDED_SERVICE = "ADDED_SERVICE";
export const VIEW_SERVICE_CLICK = "VIEW_SERVICE_CLICK";//Client-side

//slides
export const SLIDE_LIST = "SLIDE_LIST";
export const ADDED_SLIDE = "ADDED_SLIDE";

//tracking  :: shipments
export const TRACKING_NUMBER_GENERATED = "TRACKING_NUMBER_GENERATED";
export const ACCOUNT_FETCHED_BY_GSN = "ACCOUNT_FETCHED_BY_GSN";
export const REFRESH_GSN_ACCOUNT = "REFRESH_GSN_ACCOUNT";
export const NEW_SHIPMENT_CREATED = "NEW_SHIPMENT_CREATED";
export const SHIPMENTS_FETCHED = "SHIPMENTS_FETCHED";
export const LABEL_CLICKED = "LABEL_CLICKED";
export const SHOW_LABEL_OPTIONS = "SHOW_LABEL_OPTIONS";
export const SHOW_INVOICE_BUBBLE = "SHOW_INVOICE_BUBBLE";
export const INVOICE_CREATED = "INVOICE_CREATED";
export const INVOICE_FETCHED = "INVOICE_FETCHED";
export const SHIPMENTS_PROGRESS_FETCHED = "SHIPMENTS_PROGRESS_FETCHED";
export const ADD_PROGRESS_CLICKED = "ADD_PROGRESS_CLICKED";

export const INCORRECT_TRACKING_NUMBER = "INCORRECT_TRACKING_NUMBER";//Client Side tracking
export const TRACKING_REQUEST_SENT = "TRACKING_REQUEST_SENT";//Client Side tracking
export const CLIENT_SHIPMENT_FETCHED = "CLIENT_SHIPMENT_FETCHED";//Client Side tracking
export const TOGGLE_SHIPMENT_PROGRESS = "TOGGLE_SHIPMENT_PROGRESS";//Client Side tracking
export const TRACKING_VIEW_STYLE = "TRACKING_VIEW_STYLE";//Client Side tracking

//Dashboard
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const NAVIGATE_DASHBOARD = "NAVIGATE_DASHBOARD";
export const SHOW_FEEDBACK = "SHOW_FEEDBACK";
export const API_REQUEST_SENT = "API_REQUEST_SENT";
export const FETCHED_USER = "FETCHED_USER";
export const NAVIGATE_INVOICE = "NAVIGATE_INVOICE";
export const INVOICES = "INVOICES";
export const RECEIPT_UPLOAD_HANDLER = "RECEIPT_UPLOAD_HANDLER";
export const PAYMENT_UPLOADED = "PAYMENT_UPLOADED";


