export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const LOGIN_PAGE = "LOGIN_PAGE";
export const PAGE_SCROLL = "PAGE_SCROLL";
export const ADMIN_NAVIGATE = "ADMIN_NAVIGATE";
export const ACCOUNT_NAVIGATE = "ACCOUNT_NAVIGATE";
export const SHIPMENT_NAVIGATE = "SHIPMENT_NAVIGATE";
export const INPUT_HANDLER = "INPUT_HANDLER";


// Account
export const TOGGLE_ACCOUNT = "TOGGLE_ACCOUNT";
export const FETCHED_ACCOUNTS = "FETCHED_ACCOUNTS";

//Services
export const SERVICE_LIST = "SERVICE_LIST";
export const ADDED_SERVICE = "ADDED_SERVICE";

//slides
export const SLIDE_LIST = "SLIDE_LIST";
export const ADDED_SLIDE = "ADDED_SLIDE";

//tracking
export const TRACKING_NUMBER_GENERATED = "TRACKING_NUMBER_GENERATED";
export const ACCOUNT_FETCHED_BY_GSN = "ACCOUNT_FETCHED_BY_GSN";
export const REFRESH_GSN_ACCOUNT = "REFRESH_GSN_ACCOUNT";
export const NEW_SHIPMENT_CREATED = "NEW_SHIPMENT_CREATED";
export const SHIPMENTS_FETCHED = "SHIPMENTS_FETCHED";
export const LABEL_CLICKED = "LABEL_CLICKED";
export const SHIPMENTS_PROGRESS_FETCHED = "SHIPMENTS_PROGRESS_FETCHED";

